config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'weather/show', to: 'weather#show', as: 'weather'
  root 'welcom#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
    def show
        response = ::WeatherApi.get_weather(params[:city])
        if response.success?
          @weather_data = response.parsed_response
          @current_time = Time.zone.at(@weather_data['dt']).strftime('%Y-%m-%d %H:%M:%S')
        else
          flash[:error] = 'Could not retrieve weather data'
          redirect_to root_path
        end
      end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
    def show 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WheatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/show.html.erb
<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% else %>
  <h1>Weather Forecast for <%= @weather_data['name'] %></h1>
  <p>Temperature: <%= @weather_data['main']['temp'] %>°C</p>
  <p>Description: <%= @weather_data['weather'][0]['description'] %></p>
  <p>Icon: <img src="http://openweathermap.org/img/w/<%= @weather_data['weather'][0]['icon'] %>.png" alt="Weather Icon"></p>
  <p>Time: <%= @current_time %></p>
<% end %>

app/views/welcom/index.html.erb
<h1>Weather Forecast App</h1>

<%= form_tag(weather_path, method: :get) do %>
  <%= text_field_tag :city, nil, placeholder: 'Enter city name...' %>
  <%= submit_tag 'Get Weather' %>
<% end %>